### ISSUE TITLE
address React render warning

### ISSUE THREAD

**Issue by cvan** [cvan/taro#28]
```
Warning: render(): Target node has markup rendered by React, but there are unrelated nodes as well. This is most commonly caused by white-space inserted around server-rendered markup.
```

**Comment by theverything** [comment]
Found your issue while doing a google search on the warning. I figured out how to solve it so I thought I would pass it along.

In your index.html template change this.

``` html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" type="text/css" href="//code.cdn.mozilla.net/fonts/fira.css">
    <link rel="stylesheet" type="text/css" href="/static/main.css">
    <title>{{{title}}}</title>
  </head>
  <body>
    <div id='app'>{{{content}}}</div> <!-- Add this -->
    <script src="/static/main.js"></script>
  </body>
</html>
```

In your main.js change this.

``` javascript
var React = require('react');
var Router = require('react-router');

var routes = require('./routes');


Router.run(routes, Router.HistoryLocation, function (Handler) {
  React.render(<Handler/>, document.getElementById('app')); // <-- Add this
});
```

Seems like React doesn't like text nodes (created by the extra whitespace).

Hope this helps.

**Comment by cvan** [comment]
heh, thanks so much for taking the time to share your solution. I appreciate it!

**Comment by theverything** [comment]
No problem. I couldn't figure it out. My markup looked like this.

``` html
<!doctype html>
<html>
  <head>
    <title>{{{title}}}</title>
  </head>
  <body>
    <div id='app'>
        {{{content}}}
    </div>
  </body>
</html>
```

And I couldn't figure out what the issue was. Once I removed the line breaks React stopped complaining.

**Comment by topheman** [comment]
I wrapped my markup tag with div tags and the warning disappeared

``` html
<div><%- markup %></div>
```

**Comment by thangchung** [comment]
@topheman  Yes, that's true. I fixed the issue like this by add the div wrapper around my DOMs

**Comment by schtauffen** [comment]
I'm still receiving this error if I don't wrap an extra div around the react-rendered output.

**Comment by calacianu** [comment]
> I wrapped my markup tag with div tags and the warning disappeared
> 
> ```
> <div><%- markup %></div>
> ```

your solution worked for me also :)
